# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Game_Window(object):
    def setupUi(self, Game_Window):
        Game_Window.setObjectName("Game_Window")
        Game_Window.resize(1302, 900)
        Game_Window.setMinimumSize(QtCore.QSize(1302, 653))
        Game_Window.setMaximumSize(QtCore.QSize(1302, 900))
        Game_Window.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Mancala-fun-entertainment-game-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Game_Window.setWindowIcon(icon)
        Game_Window.setStyleSheet("background:#30475e    ;\n"
"border-radius:12px;")
        self.centralwidget = QtWidgets.QWidget(Game_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_p11 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_p11.setGeometry(QtCore.QRect(290, 510, 101, 81))
        self.btn_p11.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#e8e8e8;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_p11.setObjectName("btn_p11")
        self.btn_p12 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_p12.setGeometry(QtCore.QRect(410, 510, 101, 81))
        self.btn_p12.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#e8e8e8;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_p12.setObjectName("btn_p12")
        self.btn_p13 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_p13.setGeometry(QtCore.QRect(530, 510, 101, 81))
        self.btn_p13.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#e8e8e8;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_p13.setObjectName("btn_p13")
        self.btn_p14 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_p14.setGeometry(QtCore.QRect(650, 510, 101, 81))
        self.btn_p14.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#e8e8e8;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_p14.setObjectName("btn_p14")
        self.btn_p15 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_p15.setGeometry(QtCore.QRect(770, 510, 101, 81))
        self.btn_p15.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#e8e8e8;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_p15.setObjectName("btn_p15")
        self.btn_p16 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_p16.setGeometry(QtCore.QRect(890, 510, 101, 81))
        self.btn_p16.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#e8e8e8;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_p16.setObjectName("btn_p16")
        self.btn_p24 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_p24.setGeometry(QtCore.QRect(530, 360, 101, 81))
        self.btn_p24.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#ff7b54;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_p24.setObjectName("btn_p24")
        self.btn_p25 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_p25.setGeometry(QtCore.QRect(410, 360, 101, 81))
        self.btn_p25.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#ff7b54;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_p25.setObjectName("btn_p25")
        self.btn_p23 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_p23.setGeometry(QtCore.QRect(650, 360, 101, 81))
        self.btn_p23.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#ff7b54;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_p23.setObjectName("btn_p23")
        self.btn_p22 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_p22.setGeometry(QtCore.QRect(770, 360, 101, 81))
        self.btn_p22.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#ff7b54;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_p22.setObjectName("btn_p22")
        self.btn_p26 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_p26.setGeometry(QtCore.QRect(290, 360, 101, 81))
        self.btn_p26.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#ff7b54;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_p26.setObjectName("btn_p26")
        self.btn_p21 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_p21.setGeometry(QtCore.QRect(890, 360, 101, 81))
        self.btn_p21.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#ff7b54;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_p21.setObjectName("btn_p21")
        self.txt_player2_score = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_player2_score.setEnabled(True)
        self.txt_player2_score.setGeometry(QtCore.QRect(40, 270, 231, 361))
        self.txt_player2_score.setStyleSheet("font: 40pt \\\"MV Boli\\\";\n"
"background:#ff7b54;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.txt_player2_score.setInputMask("")
        self.txt_player2_score.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_player2_score.setReadOnly(True)
        self.txt_player2_score.setObjectName("txt_player2_score")
        self.txt_player1_score = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_player1_score.setEnabled(True)
        self.txt_player1_score.setGeometry(QtCore.QRect(1010, 280, 231, 361))
        self.txt_player1_score.setStyleSheet("font: 40pt \\\"MV Boli\\\";\n"
"background:#e8e8e8;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.txt_player1_score.setInputMask("")
        self.txt_player1_score.setMaxLength(32767)
        self.txt_player1_score.setFrame(True)
        self.txt_player1_score.setCursorPosition(1)
        self.txt_player1_score.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_player1_score.setReadOnly(True)
        self.txt_player1_score.setObjectName("txt_player1_score")
        self.lbl_turn = QtWidgets.QLabel(self.centralwidget)
        self.lbl_turn.setGeometry(QtCore.QRect(70, 720, 281, 61))
        self.lbl_turn.setStyleSheet("font: 25pt \\\"MV Boli\\\";\n"
"color:#222831;\n"
"")
        self.lbl_turn.setText("")
        self.lbl_turn.setObjectName("lbl_turn")
        self.lbl_level = QtWidgets.QLabel(self.centralwidget)
        self.lbl_level.setGeometry(QtCore.QRect(620, 720, 281, 61))
        self.lbl_level.setStyleSheet("font: 25pt \\\"MV Boli\\\";\n"
"color:#222831;\n"
"")
        self.lbl_level.setText("")
        self.lbl_level.setObjectName("lbl_level")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(120, 110, 401, 101))
        font = QtGui.QFont()
        font.setFamily("Neo Tech Alt")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("color:#222831;\n"
"")
        self.lbl_title.setObjectName("lbl_title")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(520, -100, 531, 481))
        self.label.setObjectName("label")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(1080, 710, 101, 81))
        self.btn_exit.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#ffe054;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_exit.setObjectName("btn_exit")
        self.btn_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next.setGeometry(QtCore.QRect(570, 620, 211, 81))
        self.btn_next.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#ffe054;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_next.setObjectName("btn_next")
        self.label.raise_()
        self.btn_p11.raise_()
        self.btn_p12.raise_()
        self.btn_p13.raise_()
        self.btn_p14.raise_()
        self.btn_p15.raise_()
        self.btn_p16.raise_()
        self.btn_p24.raise_()
        self.btn_p25.raise_()
        self.btn_p23.raise_()
        self.btn_p22.raise_()
        self.btn_p26.raise_()
        self.btn_p21.raise_()
        self.txt_player2_score.raise_()
        self.txt_player1_score.raise_()
        self.lbl_turn.raise_()
        self.lbl_level.raise_()
        self.lbl_title.raise_()
        self.btn_exit.raise_()
        self.btn_next.raise_()
        Game_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Game_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1302, 26))
        self.menubar.setObjectName("menubar")
        Game_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Game_Window)
        self.statusbar.setObjectName("statusbar")
        Game_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Game_Window)
        QtCore.QMetaObject.connectSlotsByName(Game_Window)

    def retranslateUi(self, Game_Window):
        _translate = QtCore.QCoreApplication.translate
        Game_Window.setWindowTitle(_translate("Game_Window", "Mancala"))
        self.btn_p11.setText(_translate("Game_Window", "4"))
        self.btn_p12.setText(_translate("Game_Window", "4"))
        self.btn_p13.setText(_translate("Game_Window", "4"))
        self.btn_p14.setText(_translate("Game_Window", "4"))
        self.btn_p15.setText(_translate("Game_Window", "4"))
        self.btn_p16.setText(_translate("Game_Window", "4"))
        self.btn_p24.setText(_translate("Game_Window", "4"))
        self.btn_p25.setText(_translate("Game_Window", "4"))
        self.btn_p23.setText(_translate("Game_Window", "4"))
        self.btn_p22.setText(_translate("Game_Window", "4"))
        self.btn_p26.setText(_translate("Game_Window", "4"))
        self.btn_p21.setText(_translate("Game_Window", "4"))
        self.txt_player2_score.setText(_translate("Game_Window", "0"))
        self.txt_player1_score.setText(_translate("Game_Window", "0"))
        self.lbl_title.setText(_translate("Game_Window", "MANCALA"))
        self.label.setText(_translate("Game_Window", "<html><head/><body><p><img src=\":/newPrefix/Mancala-fun-entertainment-game-512.png\"/></p></body></html>"))
        self.btn_exit.setText(_translate("Game_Window", "Exit"))
        self.btn_next.setText(_translate("Game_Window", "Next Move"))
import 1_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Game_Window = QtWidgets.QMainWindow()
    ui = Ui_Game_Window()
    ui.setupUi(Game_Window)
    Game_Window.show()
    sys.exit(app.exec_())
