# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'level_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import showings

class Ui_Level_Window(object):
    def __init__(self,mode,stealing):
        self.mode=mode
        self.stealing = stealing
        # print(stealing)

    def setupUi(self, Level_Window):
        self.Level_Window=Level_Window
        Level_Window.setObjectName("Level_Window")
        Level_Window.resize(882, 568)
        Level_Window.setMaximumSize(QtCore.QSize(882, 568))
        Level_Window.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Mancala-fun-entertainment-game-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Level_Window.setWindowIcon(icon)
        Level_Window.setStyleSheet("background:#30475e    ;\n"
"border-radius:12px;")
        self.centralwidget = QtWidgets.QWidget(Level_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(400, 60, 321, 101))
        font = QtGui.QFont()
        font.setFamily("Neo Tech Alt")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("color:#222831;\n"
"")
        self.lbl_title.setObjectName("lbl_title")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, -10, 301, 241))
        self.label.setObjectName("label")
        ###
        self.radioButton_p1_first = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_p1_first.setGeometry(QtCore.QRect(570, 250, 255, 61))
        self.radioButton_p1_first.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"color:#222831;\n"
"border-radius:12px;")
        self.radioButton_p1_first.setChecked(True)
        self.radioButton_p1_first.setObjectName("radioButton_p1_first")
        self.radioButton_ai_first = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_ai_first.setGeometry(QtCore.QRect(570, 340, 211, 61))
        self.radioButton_ai_first.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"color:#222831;\n"
"border-radius:12px;")
        self.radioButton_ai_first.setObjectName("radioButton_ai_first")
        ###
        self.btn_hard = QtWidgets.QPushButton(self.centralwidget)
        self.btn_hard.setGeometry(QtCore.QRect(220, 420, 281, 81))
        self.btn_hard.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#f5e6ca;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_hard.setObjectName("btn_hard")
        self.btn_medium = QtWidgets.QPushButton(self.centralwidget)
        self.btn_medium.setGeometry(QtCore.QRect(220, 310, 281, 81))
        self.btn_medium.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#f5e6ca;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_medium.setObjectName("btn_medium")
        self.btn_easy = QtWidgets.QPushButton(self.centralwidget)
        self.btn_easy.setGeometry(QtCore.QRect(220, 200, 281, 81))
        self.btn_easy.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#f5e6ca;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_easy.setObjectName("btn_easy")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(50, 420, 91, 81))
        self.btn_back.setStyleSheet("font: 20pt \\\"MV Boli\\\";\n"
"background:#f5e6ca;\n"
"color:#222831;\n"
"border-radius:12px;")
        self.btn_back.setObjectName("btn_back")
        self.label.raise_()
        self.lbl_title.raise_()
        self.btn_hard.raise_()
        self.btn_medium.raise_()
        self.btn_easy.raise_()
        self.btn_back.raise_()
        self.radioButton_p1_first.raise_()
        self.radioButton_ai_first.raise_()
        Level_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Level_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 882, 26))
        self.menubar.setObjectName("menubar")
        Level_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Level_Window)
        self.statusbar.setObjectName("statusbar")
        Level_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Level_Window)
        QtCore.QMetaObject.connectSlotsByName(Level_Window)

        ###
        self.btn_easy.clicked.connect(lambda : self.btn_click(2))
        self.btn_medium.clicked.connect(lambda : self.btn_click(5))
        self.btn_hard.clicked.connect(lambda : self.btn_click(7))

        self.btn_back.clicked.connect(self.btn_click_back)

    def retranslateUi(self, Level_Window):
        _translate = QtCore.QCoreApplication.translate
        Level_Window.setWindowTitle(_translate("Level_Window", "MainWindow"))
        self.lbl_title.setText(_translate("Level_Window", "Mancala"))
        self.label.setText(_translate("Level_Window", "<html><head/><body><p><img src=\"3312354-200.png\"/></p></body></html>"))
        self.btn_hard.setText(_translate("Level_Window", "Hard Mode"))
        self.btn_medium.setText(_translate("Level_Window", "Medium Mode"))
        self.btn_easy.setText(_translate("Level_Window", "Easy Mode"))
        self.btn_back.setText(_translate("Level_Window", "Back"))
        self.radioButton_p1_first.setText(_translate("Start_Window", "Player 1 First"))
        self.radioButton_ai_first.setText(_translate("Start_Window", "AI First"))

    def btn_click(self,no):
        if self.radioButton_p1_first.isChecked():
                s=1
        elif self.radioButton_ai_first.isChecked():
                s=-1

        self.no = no
        self.Level_Window.close()
        self.new_window, self.ui=showings.show_game_page(self.mode,self.stealing,self.no,s)


    def btn_click_back(self):
        self.Level_Window.close()
        self.back_window, self.back_ui = showings.show_start_page()

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Level_Window = QtWidgets.QMainWindow()
#     ui = Ui_Level_Window()
#     ui.setupUi(Level_Window)
#     Level_Window.show()
#     sys.exit(app.exec_())
